name: "Run case studies"
on: workflow_dispatch
jobs:
  case-studies:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        app:
          - angular-dart
          - angular2
          - angular2_es2015
          - angularjs
          - angularjs_require
          - aurelia
          - backbone
          - backbone_marionette
          - backbone_require
          - binding-scala
          - canjs
          - canjs_require
          - closure
          - cujo
          - dijon
          - dojo
          - duel
          - elm
          - emberjs
          # - emberjs_require
          - enyo_backbone
          - exoskeleton
          # - firebase-angular
          - gwt
          - jquery
          - js_of_ocaml
          - jsblocks
          - knockback
          - knockoutjs
          - knockoutjs_require
          - kotlin-react
          - lavaca_require
          - mithril
          - polymer
          - ractive
          - react
          - react-alt
          - react-backbone
          # - react-hooks
          - reagent
          - riotjs
          - scalajs-react
          - typescript-angular
          - typescript-backbone
          - typescript-react
          - vanilla-es6
          - vanillajs
          - vue

          # non-todomvc
          # - timer
    steps:
    - uses: actions/checkout@v2.3.1
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command
    - uses: cachix/cachix-action@v8
      with:
        name: quickstrom
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix show-config
    - name: Prepare nix shell
      run: |
        pushd case-studies
        nix-shell --command "echo Done"
        popd
    - name: Run test
      run: |
        pushd case-studies
        nix-shell --command "./run.py results ${{matrix.app}}"
        popd
    - name: Archive results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results-${{matrix.app}}
        path: case-studies/results/${{matrix.app}}.*.*
