name: "Run case studies"
on: workflow_dispatch
jobs:
  case-studies:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: 
          - angularjs
    steps:
    - uses: actions/checkout@v2.3.1
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command
    - uses: cachix/cachix-action@v8
      with:
        name: quickstrom
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix show-config
    - run: |
        pushd case-studies
        nix-shell --command "./run.py ${{matrix.browser}}"
        popd
