name: "Build and test"
on:
  pull_request:
  push:
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command
    - uses: cachix/cachix-action@v8
      with:
        name: quickstrom
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix show-config
    - run: nix-env -f '<nixpkgs>' -i nix-build-uncached
    - run: |
        version=$(nix-shell -p yj --command "yj -tj < pyproject.toml | jq -r '.tool.poetry.version'")
        echo "version=$version" >> $GITHUB_ENV
        echo "Version: $version"
    - run: nix-build-uncached default.nix
  
  integration-tests:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: 
          - chrome
    steps:
    - uses: actions/checkout@v2.3.1
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command
    - uses: cachix/cachix-action@v8
      with:
        name: quickstrom
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix show-config
    - run: nix-env -f '<nixpkgs>' -i nix-build-uncached
    - run: nix build -L -j1 --option sandbox relaxed --argstr browser ${{matrix.browser}} -f integration-tests/default.nix

#  build-docker:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2.3.1
#    - uses: cachix/install-nix-action@v12
#      with:
#        nix_path: nixpkgs=channel:nixos-unstable
#        extra_nix_config: |
#          experimental-features = nix-command
#    - uses: cachix/cachix-action@v8
#      with:
#        name: quickstrom
#        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
#    - run: docker login --username botstrom --password "$DOCKER_HUB_ACCESS_TOKEN"
#      if: github.ref == 'refs/heads/main'
#      env:
#        DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
#    - run: docker load -i $(nix-build --argstr git-rev $(git rev-parse HEAD) docker.nix)
#    - run: |
#        docker tag quickstrom/quickstrom:latest quickstrom/quickstrom:$version
#        docker push quickstrom/quickstrom:latest
#        docker push "quickstrom/quickstrom:${{ env.version }}"
#      if: github.ref == 'refs/heads/main'

  lint-docs:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command
    - uses: cachix/cachix-action@v8
      with:
        name: quickstrom
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build docs/default.nix
